### ISSUE TITLE
Failed to run: 

### ISSUE THREAD

**Issue by lauradls** [jtr13/cc22mw#51]
Hi Professor @jtr13 - I am unable to run color_deficiency after accepting the merge request. It says: `'The file 'color_deficiency' does not exist'`,  but I look at the branch that it was merged from and the jtr13-cc22mw-bookdown_yml and it has the file too. I also asked the student to update their our bookdown to add the '.Rmd' since I only added 'color_deficiency' by mistake. 

What next steps should I take?

https://github.com/jtr13/cc22mw/actions/runs/3475852933/jobs/5820182842

**Comment by jtr13** [comment]
That's been fixed. The current problem is extra lines in the DESCRIPTION file:

https://github.com/jtr13/cc22mw/actions/runs/3480677433/jobs/5820784742#step:5:79

**Comment by jtr13** [comment]
(Once this is fixed you can close the issue.)

**Comment by lauradls** [comment]
Thank you! Both are fixed
