### ISSUE TITLE
Failed to run

### ISSUE THREAD

**Issue by philkim72** [jtr13/cc22mw#60]
Pull Request #38 is failing to run.

**Comment by philkim72** [comment]
Initially I put SpDataLarge in the suggests list, but it seems it's a remote install.  So i put in in the remote section as Nowosad/spDataLarge, but it's still failing.  

https://rdrr.io/github/Nowosad/spDataLarge/

**Comment by jtr13** [comment]
Packages with remotes need to be both in suggests _and_ remotes.

**Comment by philkim72** [comment]
ok thank you.  btw, I don't think the instructions for the merge include how to handle the remote packages.

**Comment by jtr13** [comment]
Good point, I'll add information about dealing with remotes.

**Comment by jtr13** [comment]
For the new problem, take the `.Rmd` that's causing it out of `_bookdown.yml` and open up a new issue with all the info and what you've done to try to fix it.

**Comment by jtr13** [comment]
If the `spLargeData` is fixed you can close this issue.

**Comment by philkim72** [comment]
I am closing this issue for spDataLarge and opening a new issue for the subsequent issue.
