### ISSUE TITLE
Fail to run after merging #26 and #50

### ISSUE THREAD

**Issue by lauradls** [jtr13/cc22mw#63]
Hi Professor @jtr13 - How do I know if something should be on imports or remote? The jobs below are failing to run because the packages cannot be installed even after I followed directions [here. ](https://github.com/jtr13/cc22mw/issues/60)

What should I do? 
https://github.com/jtr13/cc22mw/actions/runs/3490278836
https://github.com/jtr13/cc22mw/actions/runs/3490329259

```

  Error: Error: <callr_remote_error: Cannot install packages:
  * local::.:
    * Can't install dependency d3heatmap
    * Can't install dependency chorddiag
  * d3heatmap: Can't find package called d3heatmap, chorddiag.
  * chorddiag: Can't find package called d3heatmap, chorddiag.>
```

**Comment by philkim72** [comment]
my understanding is if the package needs to be installed from github, it needs to go into both the suggest and remote sections.  Looking at pull request #26, the code says:

# devtools::install_github("rstudio/d3heatmap")
library(d3heatmap) # need to be installed from source

I believe in this case, suggests needs to include "d3heatmap" and remote needs to include "rstudio/d3heatmap"

**Comment by jtr13** [comment]
@lauradls It looks like you fixed this before posting the problem -- maybe you didn't see that the run had succeeded?

**Comment by lauradls** [comment]
Ahh! I see that it is updated on the website, I thought that I had to re-run the filed job and wait for it to go from red to green. 
<img width="1042" alt="Screen Shot 2022-11-17 at 3 57 55 PM" src="https://user-images.githubusercontent.com/21352287/202558358-9de3b062-8e6c-4e9d-9783-778cda1f274a.png">
